### ISSUE TITLE
Error en OpenCV  3.1.0 (make)

### ISSUE THREAD

**Issue by Ivan-Guillermo-Duarte** [tzutalin/build-opencv-for-android#8]
Hello, tengo este error, espero que me puedan ayudar, 

[ 59%] Generating opencv-310.jar
/usr/lib/jvm/java-7-openjdk-armhf/jre/lib/rt.jar: inflateFully: Unexpected end o                                                                                        f stream

BUILD FAILED
java.lang.NoClassDefFoundError: java/math/BigInteger
        at org.apache.tools.ant.types.Resource.getMagicNumber(Resource.java:58)
        at org.apache.tools.ant.types.Resource.<clinit>(Resource.java:48)
        at org.apache.tools.ant.ProjectHelper.configureProject(ProjectHelper.jav                                                                                        a:90)
        at org.apache.tools.ant.Main.runBuild(Main.java:826)
        at org.apache.tools.ant.Main.startAnt(Main.java:235)
        at org.apache.tools.ant.launch.Launcher.run(Launcher.java:280)
        at org.apache.tools.ant.launch.Launcher.main(Launcher.java:109)
Caused by: java.lang.ClassNotFoundException: java.math.BigInteger
        at java.net.URLClassLoader$1.run(URLClassLoader.java:359)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:348)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:347)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        ... 7 more

Total time: 0 seconds
java.lang.NoClassDefFoundError: java/math/BigInteger
        at org.apache.tools.ant.types.Resource.getMagicNumber(Resource.java:58)
        at org.apache.tools.ant.types.Resource.<clinit>(Resource.java:48)
        at org.apache.tools.ant.ProjectHelper.configureProject(ProjectHelper.jav                                                                                        a:90)
        at org.apache.tools.ant.Main.runBuild(Main.java:826)
        at org.apache.tools.ant.Main.startAnt(Main.java:235)
        at org.apache.tools.ant.launch.Launcher.run(Launcher.java:280)
        at org.apache.tools.ant.launch.Launcher.main(Launcher.java:109)
Caused by: java.lang.ClassNotFoundException: java.math.BigInteger
        at java.net.URLClassLoader$1.run(URLClassLoader.java:359)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:348)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:347)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        ... 7 more
java/math/BigInteger
modules/java/CMakeFiles/opencv_java.dir/build.make:12619: recipe for target 'bin                                                                                        /opencv-310.jar' failed
make[2]: *** [bin/opencv-310.jar] Error 1
CMakeFiles/Makefile2:14666: recipe for target 'modules/java/CMakeFiles/opencv_ja                                                                                        va.dir/all' failed
make[1]: *** [modules/java/CMakeFiles/opencv_java.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2

Muchas Gracias, estoy realizando en una raspberry pi

**Comment by rickythink** [comment]
try opencv3.2.0

**Comment by Ivan-Guillermo-Duarte** [comment]
gracias RickyWong33, me puedes darme una guía para la instalación de OpenCV 3.2.0. Nuevamente muchas gracias :)

**Comment by rickythink** [comment]
@Ivan-Guillermo-Duarte 
which os are you using? Ubuntu 14.04?

**Comment by Ivan-Guillermo-Duarte** [comment]
Nuevamente buenas noches RickyWong no señor, estoy utilizando el sistema de Rasbian en una raspberry pi 1 B.

**Comment by rickythink** [comment]
Actually it maybe doesn't have any matter with the version of OpenCV.

According to your error information, it more likely seems that your java environment has something wrong.

**Comment by Ivan-Guillermo-Duarte** [comment]
Eso pienso también Ricky, pero entonces como puedo solucionar a esa parte de Java, lo debo actualizar, aunque veo que la versión que tengo de Java es la 1.7.0, pero no se que me aconsejes, no se si habrá algún conflicto o error en actualizarlo, y desde luego no se como actualizar Java en sistema Rasbian en la Raspberry.
